# XENOZ Theme: xedarkz (Monochrome Void / Studio Carbon & Ice)
# Semantic Colors
background            #060606
foreground            #e4e4e7
selection_background  #242426
selection_foreground  #ffffff
cursor                #f4f4f5
cursor_text_color     #060606
active_border_color   #f4f4f5
inactive_border_color #2e2e33

# ANSI Colors
color0  #060606
color1  #f87171
color2  #86efac
color3  #fcd34d
color4  #93c5fd
color5  #cbd5e1
color6  #a1a1aa
color7  #e4e4e7

color8  #2e2e33
color9  #fca5a5
color10 #bbf7d0
color11 #fde047
color12 #bfdbfe
color13 #e2e8f0
color14 #d4d4d8
color15 #ffffff
