# XENOZ Theme: xeamethystz (Neon Amethyst / Synthwave Twilight)
# Semantic Colors
background            #08070d
foreground            #eae4f6
selection_background  #272044
selection_foreground  #ffffff
cursor                #c77dff
cursor_text_color     #08070d
active_border_color   #c77dff
inactive_border_color #382e5e

# ANSI Colors
color0  #08070d
color1  #ff4d6d
color2  #00f5d4
color3  #ffd166
color4  #70d6ff
color5  #c77dff
color6  #ff70a6
color7  #eae4f6

color8  #382e5e
color9  #ff6b8b
color10 #4cc9f0
color11 #ffe08a
color12 #90e0ef
color13 #d896ff
color14 #ff8cb8
color15 #ffffff
