# XENOZ Theme: xeoceanz (Abyssal Ocean / Midnight Cyan Abyss)
# Semantic Colors
background            #06090f
foreground            #e1ecf7
selection_background  #192b45
selection_foreground  #ffffff
cursor                #38bdf8
cursor_text_color     #06090f
active_border_color   #38bdf8
inactive_border_color #1f375a

# ANSI Colors
color0  #06090f
color1  #f87171
color2  #6ee7b7
color3  #fbbf24
color4  #38bdf8
color5  #818cf8
color6  #2dd4bf
color7  #e1ecf7

color8  #1f375a
color9  #fca5a5
color10 #a7f3d0
color11 #fde047
color12 #60a5fa
color13 #a5b4fc
color14 #5eead4
color15 #ffffff
