# XENOZ Theme: xeswampz (Moss Emerald / Forest Matrix)
# Semantic Colors
background            #070a08
foreground            #e0ebe2
selection_background  #1c2b20
selection_foreground  #ffffff
cursor                #34d399
cursor_text_color     #070a08
active_border_color   #34d399
inactive_border_color #243b2a

# ANSI Colors
color0  #070a08
color1  #f87171
color2  #34d399
color3  #facc15
color4  #2dd4bf
color5  #6ee7b7
color6  #86efac
color7  #e0ebe2

color8  #243b2a
color9  #fca5a5
color10 #6ee7b7
color11 #fde047
color12 #5eead4
color13 #a7f3d0
color14 #bbf7d0
color15 #ffffff
